version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  postgres:
    image: postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
